# CI action that can either run:
# - via a manual trigger on a PR
# - every time a PR is updated
# The CI then then either updates the readme with a python script,
# or checks that it does not need update.

name: Update Readme

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install your-required-packages

      - name: Run update script
        run: python update-readme.py
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes if manually triggered
        if: github.event_name == 'workflow_dispatch' && steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md"
          git push origin ${{ github.head_ref }}

      - name: Error if changes needed on PR
        if: github.event_name == 'pull_request' && steps.git-check.outputs.changes == 'true'
        run: |
          echo "Error: README.md needs to be updated. Please run this workflow manually to update it."
          exit 1
